// <auto-generated />
using System;
using FulSpectrum.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FulSpectrum.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FulSpectrumDbContext))]
    [Migration("20260314151157_ResyncSeedProducts")]
    partial class ResyncSeedProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FulSpectrum.Domain.Catalog.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Carts", (string)null);
                });

            modelBuilder.Entity("FulSpectrum.Domain.Catalog.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("CartId", "ProductId")
                        .IsUnique();

                    b.ToTable("CartItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_CartItems_Quantity", "[Quantity] >= 1");
                        });
                });

            modelBuilder.Entity("FulSpectrum.Domain.Catalog.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("nvarchar(140)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("IsActive", "Name");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("30d0f5fa-c46f-4df0-82c5-f39b4af6f1d2"),
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Devices and gadgets",
                            IsActive = true,
                            Name = "Electronics",
                            Slug = "electronics"
                        },
                        new
                        {
                            Id = new Guid("6ac41c49-72f2-4ee2-a9ac-4f612869321b"),
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Home essentials",
                            IsActive = true,
                            Name = "Home",
                            Slug = "home"
                        });
                });

            modelBuilder.Entity("FulSpectrum.Domain.Catalog.InventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("QuantityOnHand")
                        .HasColumnType("int");

                    b.Property<int>("ReorderThreshold")
                        .HasColumnType("int");

                    b.Property<int>("ReservedQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("VariantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VariantId")
                        .IsUnique();

                    b.ToTable("Inventory", null, t =>
                        {
                            t.HasCheckConstraint("CK_Inventory_QuantityOnHand", "[QuantityOnHand] >= 0");

                            t.HasCheckConstraint("CK_Inventory_ReorderThreshold", "[ReorderThreshold] >= 0");

                            t.HasCheckConstraint("CK_Inventory_ReservedQuantity", "[ReservedQuantity] >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("4fcd4fbc-4c8b-49ca-8d66-77dcac0a8475"),
                            QuantityOnHand = 120,
                            ReorderThreshold = 10,
                            ReservedQuantity = 4,
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            VariantId = new Guid("cc589f42-5ff4-40e8-ad89-c4f80d60af60")
                        },
                        new
                        {
                            Id = new Guid("d4f8c27d-5e6c-45f5-bd66-c7379a8b0452"),
                            QuantityOnHand = 90,
                            ReorderThreshold = 10,
                            ReservedQuantity = 3,
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            VariantId = new Guid("6cce416a-16b0-4dd3-8852-7f69f0f304f4")
                        },
                        new
                        {
                            Id = new Guid("f86fda30-5ae7-40de-a979-cab72a24353f"),
                            QuantityOnHand = 55,
                            ReorderThreshold = 8,
                            ReservedQuantity = 1,
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            VariantId = new Guid("d49631cf-bd4f-418f-b425-d85fa6ea2a7a")
                        });
                });

            modelBuilder.Entity("FulSpectrum.Domain.Catalog.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("CategoryId", "IsPublished");

                    b.ToTable("Products", null, t =>
                        {
                            t.HasCheckConstraint("CK_Products_BasePrice", "[BasePrice] >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("ec5ba7d8-03a6-4a15-a97c-41f7f7cc8d79"),
                            BasePrice = 149.99m,
                            CategoryId = new Guid("30d0f5fa-c46f-4df0-82c5-f39b4af6f1d2"),
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            IsPublished = true,
                            Name = "Pulse ANC Headphones",
                            Sku = "PULSE-ANC",
                            Slug = "pulse-anc-headphones"
                        },
                        new
                        {
                            Id = new Guid("9fdb4abb-6d98-4f1f-a3ac-9034b40f6de2"),
                            BasePrice = 79.50m,
                            CategoryId = new Guid("6ac41c49-72f2-4ee2-a9ac-4f612869321b"),
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            IsPublished = true,
                            Name = "Aura Desk Lamp",
                            Sku = "AURA-LAMP",
                            Slug = "aura-desk-lamp"
                        });
                });

            modelBuilder.Entity("FulSpectrum.Domain.Catalog.ProductVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<decimal>("PriceDelta")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VariantSku")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("VariantSku")
                        .IsUnique();

                    b.HasIndex("ProductId", "IsDefault");

                    b.ToTable("Variants", null, t =>
                        {
                            t.HasCheckConstraint("CK_Variants_PriceDelta", "[PriceDelta] >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("cc589f42-5ff4-40e8-ad89-c4f80d60af60"),
                            IsDefault = true,
                            Name = "Black",
                            PriceDelta = 0m,
                            ProductId = new Guid("ec5ba7d8-03a6-4a15-a97c-41f7f7cc8d79"),
                            VariantSku = "PULSE-ANC-BLK"
                        },
                        new
                        {
                            Id = new Guid("6cce416a-16b0-4dd3-8852-7f69f0f304f4"),
                            IsDefault = false,
                            Name = "White",
                            PriceDelta = 5m,
                            ProductId = new Guid("ec5ba7d8-03a6-4a15-a97c-41f7f7cc8d79"),
                            VariantSku = "PULSE-ANC-WHT"
                        },
                        new
                        {
                            Id = new Guid("d49631cf-bd4f-418f-b425-d85fa6ea2a7a"),
                            IsDefault = true,
                            Name = "Warm Light",
                            PriceDelta = 0m,
                            ProductId = new Guid("9fdb4abb-6d98-4f1f-a3ac-9034b40f6de2"),
                            VariantSku = "AURA-LAMP-WARM"
                        });
                });

            modelBuilder.Entity("FulSpectrum.Domain.Identity.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.HasIndex("IsActive", "CreatedAtUtc");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("FulSpectrum.Domain.Identity.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UsedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("FulSpectrum.Domain.Identity.RefreshSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("JwtId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ReplacedBySessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshSessions");
                });

            modelBuilder.Entity("FulSpectrum.Domain.Catalog.Cart", b =>
                {
                    b.HasOne("FulSpectrum.Domain.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FulSpectrum.Domain.Catalog.CartItem", b =>
                {
                    b.HasOne("FulSpectrum.Domain.Catalog.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FulSpectrum.Domain.Catalog.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FulSpectrum.Domain.Catalog.InventoryItem", b =>
                {
                    b.HasOne("FulSpectrum.Domain.Catalog.ProductVariant", "Variant")
                        .WithOne("Inventory")
                        .HasForeignKey("FulSpectrum.Domain.Catalog.InventoryItem", "VariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("FulSpectrum.Domain.Catalog.Product", b =>
                {
                    b.HasOne("FulSpectrum.Domain.Catalog.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FulSpectrum.Domain.Catalog.ProductVariant", b =>
                {
                    b.HasOne("FulSpectrum.Domain.Catalog.Product", "Product")
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FulSpectrum.Domain.Identity.PasswordResetToken", b =>
                {
                    b.HasOne("FulSpectrum.Domain.Identity.AppUser", "User")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FulSpectrum.Domain.Identity.RefreshSession", b =>
                {
                    b.HasOne("FulSpectrum.Domain.Identity.AppUser", "User")
                        .WithMany("RefreshSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FulSpectrum.Domain.Catalog.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("FulSpectrum.Domain.Catalog.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("FulSpectrum.Domain.Catalog.Product", b =>
                {
                    b.Navigation("Variants");
                });

            modelBuilder.Entity("FulSpectrum.Domain.Catalog.ProductVariant", b =>
                {
                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("FulSpectrum.Domain.Identity.AppUser", b =>
                {
                    b.Navigation("PasswordResetTokens");

                    b.Navigation("RefreshSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
